#= require hamlcoffee
#= require lib/jquery
#= require lib/lodash.underscore
#= require lib/backbone
#= require lib/backbone.marionette
#= require setup
#= require_tree ./templates
#= require_tree ./views
#= require_self
